#!/bin/sh

TAG='lay'
TAG_COLOR=$(xgetres dwmblocks.tagcolor) || TAG_COLOR='#ffffff'
COLOR=$(xgetres dwmblocks.keyboard_layout_col) || COLOR='#00ff00'

if setxkbmap -query | grep -Gq "layout:\s*de"
then
	layout='de'
else if setxkbmap -query | grep -Gq "layout:\s*us"
	then
		layout='us'
	else
		layout='?'
	fi
fi

printf ' ^c%s^%s ^c%s^%s ' "$TAG_COLOR" "$TAG" "$COLOR" "$layout"
