#!/bin/bash

volume=$(pamixer --get-volume)

speakers=$(pamixer --get-mute | sed 's/false/A/;s/true/M/')

TAG=$(xgetres dwmblocks.tagcolor)
COLOR=$(xgetres dwmblocks.volume_col)

printf ' ^c%s^VOL ^c%s^%3s%% %s %s ' "$TAG" "$COLOR" "$volume" "$speakers"
