#!/bin/sh

time=$(date '+%a %Y-%m-%d %R:%S')

TAG=$(xgetres dwmblocks.tagcolor) || TAG='#ffffff'
COLOR=$(xgetres dwmblocks.date_col) || COLOR='#00ffff'

printf ' ^c%s^DAT ^c%s^%s ' "$TAG" "$COLOR" "$time"
