#!/bin/sh

TAG='dat'
TAG_COLOR=$(xgetres dwmblocks.tagcolor) || TAG_COLOR='#ffffff'
COLOR=$(xgetres dwmblocks.date_col) || COLOR='#00ffff'

time=$(date '+%a %Y-%m-%d %R:%S')

printf ' ^c%s^%s ^c%s^%s ' "$TAG_COLOR" "$TAG" "$COLOR" "$time"
