#!/bin/sh

TAG='net'
TAG_COLOR=$(xgetres dwmblocks.tagcolor) || TAG_COLOR='#ffffff'
COLOR=$(xgetres dwmblocks.network_col) || COLOR='#ffff00'

conname=$(nmcli -a | grep 'Wired connection' | awk 'NR==1{print $1}')
[ "$conname" = '' ] && conname=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)

private=$(nmcli -a | grep 'inet4 192' | awk '{print $2}')
public=$(curl -s https://ipinfo.io/ip)

if [ "$conname" = '' ]; then
  printf ' ^c%s^%s ^c%s^%s ' "$TAG_COLOR" "$TAG" "$COLOR" 'No connection'
else
  if [ "$public" = '' ]; then
    printf ' ^c%s^%s ^c%s^%s: %s - %s ' "$TAG_COLOR" "$TAG" "$COLOR" "$conname" "$private" 'No public IP detected'
  else
    printf ' ^c%s^%s ^c%s^%s: %s - %s ' "$TAG_COLOR" "$TAG" "$COLOR" "$conname" "$private" "$public"
  fi
fi
