#!/bin/bash

CONNAME=$(nmcli -a | grep 'Wired connection' | awk 'NR==1{print $1}')
[ "$CONNAME" = '' ] && CONNAME=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -c 5-)

PRIVATE=$(nmcli -a | grep 'inet4 192' | awk '{print $2}')
PUBLIC=$(curl -s https://ipinfo.io/ip)

TAG=$(xgetres dwmblocks.tagcolor)
COLOR=$(xgetres dwmblocks.network_col)

if [ "$CONNAME" = '' ]; then
  printf ' ^c%s^NET ^c%s^Not connected ' "$TAG" "$COLOR"
else
  if [ "$PUBLIC" = '' ]; then
    printf ' ^c%s^NET ^c%s^%s: %s - %s ' "$TAG" "$COLOR" "$CONNAME" "$PRIVATE" 'No public IP detected'
  else
    printf ' ^c%s^NET ^c%s^%s: %s - %s ' "$TAG" "$COLOR" "$CONNAME" "$PRIVATE" "$PUBLIC"
  fi
fi
