#!/bin/sh

TAG=$(xgetres dwmblocks.tagcolor)
COLOR=$(xgetres dwmblocks.keyboard_layout_col)

if setxkbmap -query | grep -Gq "layout:\s*de"
then
	layout='De'
else
	layout='Us'
fi

printf ' ^c%s^LAY ^c%s^%s ' "$TAG" "$COLOR" "$layout"
